# Data from Nvidia GB200 NVL72 w/ 16x GPUs
# https://github.com/mlcommons/training_results_v5.1/blob/main/NVIDIA/systems/tyche_ngpu16_ngc25.09_nemo.json
# https://github.com/mlcommons/training_results_v5.1/blob/main/NVIDIA/results/tyche_ngpu16_ngc25.09_nemo/flux1/result_0.txt
#num_samples: 261120
#time_ms: 288574
#global_batch_size: 512
#batches: 510
#ms_per_batch: 565.8

model:
  name: parquet

framework: pytorch

workflow:
  generate_data: False
  train: True

dataset:
  data_folder: /mnt/nvme/data/parquet
  format: parquet
  compression: none
  num_files_train: 2400
  num_samples_per_file: 256
  parquet_row_group_size: 64
  record_length: 2164833
  record_length_stdev: 0
  record_length_resize: 0

  # Parquet-specific field specifications
  parquet_field_specs:
    t5_encodings:
      dtype: bytes
      length: 2097313
      variable_length: False
      read: True
    clip_encodings:
      dtype: bytes
      length: 1634
      variable_length: False
      read: True
    mean:
      dtype: bytes
      length: 32929
      read: False
    logvar:
      dtype: bytes
      length: 32929
      read: False
    timestep:
      dtype: bytes
      length: 28
      read: True

reader:
  data_loader: pytorch
  batch_size: 48
  read_threads: 4
  file_shuffle: seed
#  sample_shuffle: seed
  prefetch_size: 2

train:
  epochs: 1
  computation_time: 0.847

metric:
  au: 0.90


# Ideal samples per second = <batch_size> / <computation_time>
# 48 / 0.847 = 56.67
# 32 / 0.565 = 56.64